In [32]:
from tensorflow.keras.preprocessing.text import one_hot

In [33]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [34]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [35]:
#Define the vocabulary size

voc_size = 10000

In [36]:
#One hot representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[873, 7905, 3167, 7211],
 [873, 7905, 3167, 1338],
 [873, 5848, 3167, 1755],
 [7442, 8590, 9972, 7427, 9235],
 [7442, 8590, 9972, 7427, 6996],
 [3738, 873, 1192, 3167, 8994],
 [7682, 6466, 6846, 7427]]

In [37]:
#Word embedding reprensentation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [38]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  873 7905 3167 7211]
 [   0    0    0    0  873 7905 3167 1338]
 [   0    0    0    0  873 5848 3167 1755]
 [   0    0    0 7442 8590 9972 7427 9235]
 [   0    0    0 7442 8590 9972 7427 6996]
 [   0    0    0 3738  873 1192 3167 8994]
 [   0    0    0    0 7682 6466 6846 7427]]


In [39]:
#Feature representation
dim=10

In [40]:
model=Sequential()
model.add(Embedding(input_dim=voc_size,output_dim=dim,input_length=sent_length))
model.compile('adam','mse')

In [43]:
model.build(input_shape=(None, sent_length))
model.summary()


Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [51]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 7s 7s/step


array([[[ 0.00631131, -0.02472417,  0.02781406, -0.03017596,
         -0.0240024 , -0.00967314,  0.04742329, -0.04267624,
         -0.01953292, -0.00551572],
        [ 0.00631131, -0.02472417,  0.02781406, -0.03017596,
         -0.0240024 , -0.00967314,  0.04742329, -0.04267624,
         -0.01953292, -0.00551572],
        [ 0.00631131, -0.02472417,  0.02781406, -0.03017596,
         -0.0240024 , -0.00967314,  0.04742329, -0.04267624,
         -0.01953292, -0.00551572],
        [ 0.00631131, -0.02472417,  0.02781406, -0.03017596,
         -0.0240024 , -0.00967314,  0.04742329, -0.04267624,
         -0.01953292, -0.00551572],
        [-0.00046655, -0.03040663, -0.04470432, -0.00493444,
          0.00192796,  0.03575547,  0.04660046, -0.02842805,
         -0.01888347, -0.0463462 ],
        [-0.03019087,  0.04999674, -0.04200735, -0.01297283,
          0.02265311,  0.02156099,  0.03035388,  0.00427235,
          0.02857793, -0.03496965],
        [-0.02539612,  0.0431619 , -0.01024552,  0.0

In [48]:
embedded_docs[0]

array([   0,    0,    0,    0,  873, 7905, 3167, 7211])

In [50]:
model.predict(embedded_docs[0][0])

IndexError: tuple index out of range